# Generated by Django 5.0.7 on 2024-07-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeTarantino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField()),
                ('onde_assistir', models.CharField(max_length=255)),
                ('elenco', models.TextField()),
            ],
        ),
    ]
