# Generated by Django 5.0.7 on 2024-07-23 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ano_lancamento', models.IntegerField(verbose_name='Ano de Lançamento')),
                ('onde_assistir', models.CharField(max_length=100, verbose_name='Onde Assistir')),
                ('elenco', models.TextField(verbose_name='Elenco')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-ano_lancamento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Localização')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='UserFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_filmes', to='main.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filme do Usuário',
                'verbose_name_plural': 'Filmes dos Usuários',
                'unique_together': {('user', 'filme')},
            },
        ),
        migrations.DeleteModel(
            name='FilmeTarantino',
        ),
    ]
