# Generated by Django 5.0.7 on 2024-07-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cadastro_filme_profile_userfilme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.filme'),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default='Desconhecido', max_length=100, verbose_name='Diretor'),
        ),
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default='Desconhecido', max_length=300, verbose_name='Sinopse'),
        ),
    ]
