# Generated by Django 5.0.7 on 2024-07-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='filmes_favoritos',
            field=models.ManyToManyField(blank=True, to='main.filme'),
        ),
    ]
