# Generated by Django 5.0.7 on 2024-07-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_perfil_filmes_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='filmes_favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos', to='main.filme'),
        ),
    ]
